<a href="https://colab.research.google.com/github/Oloadama/Oloadama.github.io/blob/main/Data_Science_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Science Capstone Project

###Project's Objective: Analyze restaurant data to perform EDA, build predictive models, and derive actionable insights.

####1. Data Exploration
a. Dataset overview:

*   Explore dataset dimensions.
*   Check for missing values.
*   Perform data conversions as needed.

[Dataset](https://raw.githubusercontent.com/Oyeniran20/axia_class_cohort_7/refs/heads/main/Dataset%20.csv)

In [ ]:
## Importing the important libraries for these functions
import pandas as pd
import numpy as np

In [ ]:
## data loading and exploration
restaurant_df = pd.read_csv('https://raw.githubusercontent.com/Oyeniran20/axia_class_cohort_7/refs/heads/main/Dataset%20.csv')
restaurant_df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
## diplaying the whole column length.

pd.set_option('display.max_columns', None)
restaurant_df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
## dataset dimension
restaurant_df.shape

(9551, 21)

In [ ]:
## dataset information
restaurant_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
## checking for missing values
restaurant_df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
## percentage of missing values
restaurant_df.isnull().sum()/(len(restaurant_df))*100

Restaurant ID           0.000000
Restaurant Name         0.000000
Country Code            0.000000
City                    0.000000
Address                 0.000000
Locality                0.000000
Locality Verbose        0.000000
Longitude               0.000000
Latitude                0.000000
Cuisines                0.094231
Average Cost for two    0.000000
Currency                0.000000
Has Table booking       0.000000
Has Online delivery     0.000000
Is delivering now       0.000000
Switch to order menu    0.000000
Price range             0.000000
Aggregate rating        0.000000
Rating color            0.000000
Rating text             0.000000
Votes                   0.000000
dtype: float64

In [ ]:
restaurant_df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
## converting the aggregate column from object to a float
restaurant_df['Aggregate rating'] = restaurant_df['Aggregate rating'].astype(float)
restaurant_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
## checking for duplicate values
restaurant_df.duplicated().sum()

0

In [ ]:
restaurant_df.City.unique()

array(['Makati City', 'Mandaluyong City', 'Pasay City', 'Pasig City',
       'Quezon City', 'San Juan City', 'Santa Rosa', 'Tagaytay City',
       'Taguig City', 'Bras�_lia', 'Rio de Janeiro', 'S��o Paulo',
       'Albany', 'Armidale', 'Athens', 'Augusta', 'Balingup',
       'Beechworth', 'Boise', 'Cedar Rapids/Iowa City', 'Chatham-Kent',
       'Clatskanie', 'Cochrane', 'Columbus', 'Consort', 'Dalton',
       'Davenport', 'Des Moines', 'Dicky Beach', 'Dubuque',
       'East Ballina', 'Fernley', 'Flaxton', 'Forrest', 'Gainesville',
       'Hepburn Springs', 'Huskisson', 'Inverloch', 'Lakes Entrance',
       'Lakeview', 'Lincoln', 'Lorn', 'Macedon', 'Macon', 'Mayfield',
       'Mc Millan', 'Middleton Beach', 'Miller', 'Monroe', 'Montville',
       'Ojo Caliente', 'Orlando', 'Palm Cove', 'Paynesville', 'Penola',
       'Pensacola', 'Phillip Island', 'Pocatello', 'Potrero', 'Princeton',
       'Rest of Hawaii', 'Savannah', 'Singapore', 'Sioux City',
       'Tampa Bay', 'Tanunda', 'Trentham East', 'Valdosta', 'Vernonia',
       'Victor Harbor', 'Vineland Station', 'Waterloo', 'Weirton',
       'Winchester Bay', 'Yorkton', 'Abu Dhabi', 'Dubai', 'Sharjah',
       'Agra', 'Ahmedabad', 'Allahabad', 'Amritsar', 'Aurangabad',
       'Bangalore', 'Bhopal', 'Bhubaneshwar', 'Chandigarh', 'Chennai',
       'Coimbatore', 'Dehradun', 'Faridabad', 'Ghaziabad', 'Goa',
       'Gurgaon', 'Guwahati', 'Hyderabad', 'Indore', 'Jaipur', 'Kanpur',
       'Kochi', 'Kolkata', 'Lucknow', 'Ludhiana', 'Mangalore', 'Mohali',
       'Mumbai', 'Mysore', 'Nagpur', 'Nashik', 'New Delhi', 'Noida',
       'Panchkula', 'Patna', 'Puducherry', 'Pune', 'Ranchi',
       'Secunderabad', 'Surat', 'Vadodara', 'Varanasi', 'Vizag',
       'Bandung', 'Bogor', 'Jakarta', 'Tangerang', 'Auckland',
       'Wellington City', 'Birmingham', 'Edinburgh', 'London',
       'Manchester', 'Doha', 'Cape Town', 'Inner City', 'Johannesburg',
       'Pretoria', 'Randburg', 'Sandton', 'Colombo', 'Ankara',
       '��stanbul'], dtype=object)

In [ ]:
## checking how many 'Bras�_lia' is in the dataset
restaurant_df[restaurant_df['City']== 'Bras�_lia']

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
22,6600681,Chez Michou,30,Bras�_lia,"SCLN, 208, Bloco A, Loja 30, Asa Norte, Bras�_lia",Asa Norte,"Asa Norte, Bras�_lia",-47.881789,-15.764142,"Fast Food, French",55,Brazilian Real(R$),No,No,No,No,2,3.0,Orange,Average,6
23,6601005,Caf�� Daniel Briand,30,Bras�_lia,"SCLN 104, Bloco A, Loja 26, Asa Norte, Bras�_lia",Asa Norte,"Asa Norte, Bras�_lia",-47.882667,-15.777500,Cafe,30,Brazilian Real(R$),No,No,No,No,1,3.8,Yellow,Good,9
24,6600292,Casa do Biscoito Mineiro,30,Bras�_lia,"SCLN 210, Bloco D, Loja 36/48, Asa Norte, Bras...",Asa Norte,"Asa Norte, Bras�_lia",-47.882136,-15.757472,Bakery,45,Brazilian Real(R$),No,No,No,No,2,3.7,Yellow,Good,11
25,6600441,Maori,30,Bras�_lia,"CLN 110, Bloco D, Loja 28, Asa Norte, Bras�_lia",Asa Norte,"Asa Norte, Bras�_lia",-47.888167,-15.758833,Brazilian,60,Brazilian Real(R$),No,No,No,No,3,3.8,Yellow,Good,11
26,6600970,Pizza �� Bessa,30,Bras�_lia,"SCS 214, Bloco C, Loja 40, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.915667,-15.831167,Pizza,50,Brazilian Real(R$),No,No,No,No,2,3.2,Orange,Average,11
27,6600379,Sushi Loko,30,Bras�_lia,"SCS 213, Bloco C, Loja 35, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.915667,-15.831000,Japanese,80,Brazilian Real(R$),No,No,No,No,3,3.1,Orange,Average,10
28,6600214,Beirute,30,Bras�_lia,"CLS 109, Bloco A, Loja 2/6, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.907500,-15.820000,Arabian,90,Brazilian Real(R$),No,No,No,No,3,3.7,Yellow,Good,8
29,6601218,New Koto,30,Bras�_lia,"SCS 212, Bloco B, Loja 26, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.910167,-15.827333,Japanese,200,Brazilian Real(R$),No,No,No,No,4,3.7,Yellow,Good,5
30,6600060,Sandubas Caf��,30,Bras�_lia,"Edif�_cio Jos�� Severo, SCS 6, Bloco A, Loja 9...",Asa Sul,"Asa Sul, Bras�_lia",-47.890167,-15.797000,"Brazilian, Cafe",30,Brazilian Real(R$),No,No,No,No,1,0.0,White,Not rated,2
31,6600083,Villa Tevere,30,Bras�_lia,"CLS 115, Bloco A, Loja 2, Asa Sul, Bras�_lia",Asa Sul,"Asa Sul, Bras�_lia",-47.923667,-15.831333,Italian,150,Brazilian Real(R$),No,No,No,No,4,4.1,Green,Very Good,12
32,6601515,Rovereto,30,Bras�_lia,"Rua 13 Norte, Lote 4, �guas Claras, Bras�_lia",�guas Claras,"�guas Claras, Bras�_lia",-48.019000,-15.837167,Pizza,100,Brazilian Real(R$),No,No,No,No,4,3.1,Orange,Average,9
33,6601361,Buena Carne,30,Bras�_lia,"Avenida Arauc��rias, 1325, Loja 19, �guas Clar...",�guas Claras,"�guas Claras, Bras�_lia",-48.019092,-15.839775,"Bar Food, Brazilian",60,Brazilian Real(R$),No,No,No,No,3,3.6,Yellow,Good,9
34,6601602,Taco Pep,30,Bras�_lia,"Vila Malls, Avenida das Castanheiras, Lote 106...",�guas Claras,"�guas Claras, Bras�_lia",-48.016667,-15.834833,"Mexican, Grill",100,Brazilian Real(R$),No,No,No,No,4,4.3,Green,Very Good,29
35,6601589,Coco Bambu,30,Bras�_lia,"Bras�_lia Shopping - Piso 2, SCN 5, Bloco A, A...","Bras�_lia Shopping, Asa Norte","Bras�_lia Shopping, Asa Norte, Bras�_lia",-47.889000,-15.786500,International,230,Brazilian Real(R$),No,No,No,No,4,4.2,Green,Very Good,17
36,6601862,Tayp��,30,Bras�_lia,"Fashion Park, Shis Ql 17, Bloco G, Loja 208, L...",Lago Sul,"Lago Sul, Bras�_lia",-47.872359,-15.860621,"Peruvian, Latin American",100,Brazilian Real(R$),No,No,No,No,4,3.6,Yellow,Good,5
37,6601595,Outback Steakhouse,30,Bras�_lia,"ParkShopping - Piso 2, SAI/SO, �rea 6580, Guar...","ParkShopping, Guar�� I","ParkShopping, Guar�� I, Bras�_lia",-47.956283,-15.834514,"American, Grill",150,Brazilian Real(R$),No,No,No,No,4,4.0,Green,Very Good,10
38,6601158,Manzu��,30,Bras�_lia,"Pont��o Lago Sul, SHIS 10, Lote 9, Lago Sul, B...","Pont��o Lago Sul, Lago Sul","Pont��o Lago Sul, Lago Sul, Bras�_lia",-47.872833,-15.825667,Seafood,240,Brazilian Real(R$),No,No,No,No,4,3.2,Orange,Average,6
39,6600427,Coco Bambu,30,Bras�_lia,"SCES, Trecho 2, Conjunto 13/36, Setor de Clube...",Setor De Clubes Esportivos Sul,"Setor De Clubes Esportivos Sul, Bras�_lia",-47.868500,-15.819000,International,230,Brazilian Real(R$),No,No,No,No,4,4.9,Dark Green,Excellent,30
40,6600116,Gero,30,Bras�_lia,"Shopping Iguatemi - piso 1, SHIN CA 4, Lote A,...","Shopping Iguatemi, Lago Norte","Shopping Iguatemi, Lago Norte, Bras�_lia",-47.885812,-15.720118,Italian,350,Brazilian Real(R$),No,No,No,No,4,3.3,Orange,Average,8
41,6601457,Brazilian American Burgers,30,Bras�_lia,"CLSN 301, Bloco C, Loja 86, Sudoeste, Bras�_lia",Sudoeste,"Sudoeste, Bras�_lia",-47.921028,-15.797531,"American, Burger",50,Brazilian Real(R$),No,No,No,No,2,3.6,Yellow,Good,9

In [ ]:
restaurant_df.replace('Bras�_lia', 'Brasilia', inplace=True)
restaurant_df.replace('S��o Paulo', 'Sao Paulo', inplace=True)
restaurant_df.replace('��stanbul', 'Instabul', inplace=True)

In [ ]:
restaurant_df['Restaurant Name'].unique()

array(['Le Petit Souffle', 'Izakaya Kikufuji', 'Heat - Edsa Shangri-La',
       ..., 'Huqqa', 'A���k Kahve', "Walter's Coffee Roastery"],
      dtype=object)

In [ ]:
restaurant_df['Restaurant Name']

0               Le Petit Souffle
1               Izakaya Kikufuji
2         Heat - Edsa Shangri-La
3                           Ooma
4                    Sambo Kojin
                  ...
9546                 Naml۱ Gurme
9547                Ceviz A��ac۱
9548                       Huqqa
9549                 A���k Kahve
9550    Walter's Coffee Roastery
Name: Restaurant Name, Length: 9551, dtype: object

In [ ]:
restaurant_df[restaurant_df['Restaurant Name']== 'A���k Kahve']

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9549,5916112,A���k Kahve,208,Instabul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,120,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901